name: adapt_flutter
description: Adapt nutrition tracking app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '^3.8.0'
  flutter: '^3.32.0'

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  adapt_client:
    path: ../adapt_client
  adapt_theme:
    path: ../adapt_theme
  go_router: ^14.6.1
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  freezed_annotation: ^2.4.4
  sqflite: ^2.4.2
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  permission_handler: ^11.3.1
  flutter_local_notifications: ^18.0.1
  intl: ^0.20.2
  flutter_dotenv: ^5.2.1
  serverpod_auth_core_flutter: ^3.3.1

dev_dependencies:
  flutter_lints: '>=3.0.0 <7.0.0'
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.6.1
  freezed: ^2.5.7
  build_runner: ^2.4.14

flutter:
  uses-material-design: true
  assets:
    - assets/config.json
